FROM node:lts-slim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
  apt-get install -y openjdk-17-jre-headless git && \
  rm -rf /var/lib/apt/lists/*

RUN npm install -g firebase-tools@latest

RUN mkdir -p /home/node/.cache/firebase && \
  chown -R node:node /home/node/.cache

WORKDIR /workspace

RUN mkdir -p /workspace/data

COPY .firebaserc .
COPY firebase.json .
COPY firestore.rules .
COPY firestore.indexes.json .

ENTRYPOINT ["sh","-c","firebase emulators:start  --import=data"]